### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by huitc** [SageHack/cloud-buster#33]
https://play.google.com/store/apps/details?id=com.termux
```
$ python3 bust --dept full test.com

============ The =====,---/V\
==== CloudBUSTER ====~|  (o.o)
=== by @SageHack =====uu--uu

[target] test.com
* ip: 104.20.135.34 (CF yes RAY-4aefcfbaaa7c328f-HKG)
* http: cloudflare - 404 Not Found
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/data/com.termux/files/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bust/__main__.py", line 112, in <module>
    main(args)
  File "bust/__main__.py", line 27, in main
    scan(args)
  File "bust/__main__.py", line 55, in scan
    found = sub_scan(buster, args, technique)
  File "bust/__main__.py", line 65, in sub_scan
    target_found = scan_technique()
  File "bust/buster.py", line 100, in scan_mx
    mxs = MxRecords(self.domain).__get__()
  File "bust/descriptor/mxrecords.py", line 18, in __get__
    mxs = dns.resolver.query(self.domain, 'MX')
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dns/resolver.py", line 1132, in query
    raise_on_no_answer, source_port)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.003259897232056 seconds
```

```
$ uname -a
Linux localhost 4.4.78-perf-gdaac017 #1 SMP PREEMPT Fri Feb 15 18:57:51 CST 2019 aarch64 Android
```

**Comment by SageHack** [comment]
Oh, this is running on Android and using Python3.7 yeah ok. Can you try running this on Python3.5? I was coded for 3.5 so I'm guessing it should be backward compatible but, it might be something with the Android stack.

**Comment by SageHack** [comment]
I'm pretty sure that the library does not support the Android stack properly. Android is probably doing its own thing to DNS resolution. If you want to troubleshoot that, feel free to go ahead, but you'll likely have to report a bug in here https://github.com/rthalley/dnspython/issues

**Comment by SageHack** [comment]
Or it cloud simply be your network, or the Android network stack, or any other part of your network not handling DNS resolution properly `dns.exception.Timeout: The DNS operation timed out after 30.003259897232056 seconds` or test.com not resolving from your device.
Try with website you can load in your browser, or within TMUX with curl.

**Comment by huitc** [comment]
I have tried refreshing the dns cache, but still can't succeed...

**Comment by SageHack** [comment]
The problem might also be with Python 3.7. I'll have to test that out.

**Comment by SageHack** [comment]
I'm going to migrate the code base to Python 3.7 at some point. Created an issue for that #40. If that doesn't fix it, I'm guessing that compiled binaries will #38. Once those two issues have been completed, I will make sure to add an Android VMs to the test pipeline I will create on #37. So it's going to take a while before I get there but it's likely to get fixed.
