### ISSUE TITLE
DNS dumpster scan fails

### ISSUE THREAD

**Issue by SageHack** [SageHack/cloud-buster#35]
```
$ python3 bust www.commanderx.info --scan dnsdumpster

[target] www.commanderx.info
* ip: 104.28.29.224 (CF yes RAY-4da700e249bbc791-AMS)
* http: cloudflare - 301 Moved Permanently
There was an error getting results
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bust/__main__.py", line 112, in <module>
    main(args)
  File "bust/__main__.py", line 27, in main
    scan(args)
  File "bust/__main__.py", line 55, in scan
    found = sub_scan(buster, args, technique)
  File "bust/__main__.py", line 65, in sub_scan
    target_found = scan_technique()
  File "bust/buster.py", line 78, in scan_dnsdumpster
    records = results['dns_records']
TypeError: list indices must be integers or slices, not str
```

**Comment by SageHack** [comment]
Looks like DNS dumpster isn't returning what's expected from it's API anymore. It probably changed.

**Comment by SageHack** [comment]
The issue is with subdomain usage. I'm guessing that DNS dumpster only accept FQDN.
